### ISSUE TITLE
I reported an error when I started the game

### ISSUE THREAD

**Issue by 2970194508** [daleao/sdv#10]
Modular Gameplay Overhaul 4.2.2 because its DLL 'DaLion.Overhaul.dll' doesn't exist.
![1TSX@T 4CABX%0%0()T7U3](https://github.com/user-attachments/assets/a5fd00ef-c7e3-468d-8ffc-323d8dc502a9)

**Comment by daleao** [comment]
The version you used of the mod was not compatible with the version of the game.
